[graph]
all-features = false

[advisories]
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "AGPL-3.0-only",
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "allow"
allow-workspace = true
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
