[package]
name = "rpg-translator-desktop"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "rpg-translator-desktop"
path = "src/main.rs"

[dependencies]
rpg-translator-core.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.11.2" }

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
