[package]
name = "rpg-translator-core"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
hex.workspace = true
rusqlite.workspace = true
serde.workspace = true
sha2.workspace = true

[lints]
workspace = true
